version: "3"

services:
  backend:
    image: node:alpine
    working_dir: /usr/app
    volumes:
      - ./backend:/usr/app
    ports:
      - 3333:3333
    command: sh -c 'yarn install && yarn knex migrate:latest && yarn dev'

  frontend-web:
    image: node:alpine
    working_dir: /usr/app
    volumes:
      - ./frontend-web:/usr/app
    ports:
      - 3000:3000
    stdin_open: true
    command: sh -c 'yarn install && yarn start'
    depends_on:
      - backend

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.77.0.0/16
